; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F401RC]
platform = ststm32
board = genericSTM32F401RC
framework = stm32cube
build_flags = 
	-I./src/cubemx/inc
	-I./src/cubemx/USB_DEVICE/App
	-I./src/cubemx/USB_DEVICE/Target
	-D MONITOR_TASK=0
	-D UART_DEBUG=0
	-D MODBUS_SLAVE_STACK_SIZE=2048
debug_build_flags =
	-D FREERTOS
	${env.build_flags}
monitor_speed = 115200
debug_tool = stlink
upload_protocol = dfu